export const userDatabase = [
  { firstName: "John", lastName: "Doe", registered: "false" },
  { firstName: "Quadri", lastName: "Kazeem", registered: "false" },
  { firstName: "Temitope", lastName: "Macjob", registered: "false" },
  { firstName: "ololade", lastName: "kolejo", registered: "false" },
  { firstName: "adetope", lastName: "aderogba", registered: "false" },
  { firstName: "joseph", lastName: "Adekuoroye", registered: "false" },
  { firstName: "adebimpe", lastName: "adebomi", registered: "false" },
  { firstName: "joannes", lastName: "doe", registered: "false" },
  { firstName: "Ahmed", lastName: "Alamutu", registered: false },
  { firstName: "Kolawole", lastName: "Adedipe", registered: false },
  { firstName: "Cornel", lastName: "Igbokwe", registered: false },
  { firstName: "Febishola", lastName: "Owoeye-wise", registered: false },
  { firstName: "Confidence", lastName: "Duru", registered: false },
  { firstName: "Martha", lastName: "Olaoye", registered: false },
  { firstName: "Henry", lastName: "Ijeh", registered: false },
  { firstName: "Akinwunmi", lastName: "Morakinyo", registered: false },
];
